"""updated schema

Revision ID: 9189c98b4e7a
Revises: 51d162a47c75
Create Date: 2023-11-10 00:58:20.622304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9189c98b4e7a'
down_revision = '51d162a47c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('section')
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('section', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
